version: 2

tools:
  prettierd: &prettierd
    format-command: "prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd}"
    format-stdin: true

  stylua: &stylua
    format-command: "stylua --color Never --search-parent-directories ${--range-start:charStart} ${--range-end:charEnd} -"
    format-stdin: true

languages:
  javascript:
    - <<: *prettierd
  typescript:
    - <<: *prettierd
  javascriptreact:
    - <<: *prettierd
  typescriptreact:
    - <<: *prettierd
  css:
    - <<: *prettierd
  scss:
    - <<: *prettierd
  html:
    - <<: *prettierd
  json:
    - <<: *prettierd
  yaml:
    - <<: *prettierd
  markdown:
    - <<: *prettierd
  graphql:
    - <<: *prettierd
  lua:
    - <<: *stylua
