words = [
    "autoindent",
    "autotrigger",
    "bufnr",
    "colorcolumn",
    "completeopt",
    "cursorline",
    "esc",
    "expandtab",
    "hlsearch",
    "ignorecase",
    "inccommand",
    "incsearch",
    "mapleader",
    "menuone",
    "netrw",
    "nohl",
    "noselect",
    "relativenumber",
    "scrolloff",
    "shiftwidth",
    "showmatch",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitbelow",
    "splitright",
    "swapfile",
    "tabstop",
    "undofile",
    "updatetime",
    "winborder",
]
