require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.filetypes")
require("config.colorscheme")

require("plugins.treesitter")
require("plugins.spider")
require("plugins.nvim-surround")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.conform")
require("plugins.dressing")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.zen-mode")
require("plugins.nvim-spectre")
require("plugins.auto-session")
