vim.loader.enable()

require("config.options")
require("config.keymaps")
require("config.autocmds")

require("plugins.colorscheme")

require("plugins.treesitter")
require("plugins.lsp")
require("plugins.lsp-extra")
require("plugins.blink")
require("plugins.conform")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.scope")
require("plugins.telescope")
require("plugins.spider")
require("plugins.autopairs")
require("plugins.surround")
require("plugins.leap")
require("plugins.spectre")
require("plugins.copilot")
