set fish_greeting

abbr gb 'git branch'
abbr gc 'git switch'
abbr ga 'git add .'
abbr gs 'git status'
abbr gst 'git stash -u'
abbr gstl 'git stash list'
abbr gstp 'git stash pop'
abbr gm 'git commit -m'
abbr gma 'git commit --amend'
abbr gman 'git commit --amend --no-edit'
abbr gf 'git fetch'
abbr gp 'git pull'
abbr gP 'git push'
abbr gl 'git log'
abbr gd 'git diff'
abbr gdh 'git diff HEAD'
abbr gr 'git rebase -i'
abbr grc 'git rebase --continue'
abbr gra 'git rebase --abort'
abbr grs 'git restore'
abbr grss 'git restore --staged'
abbr grsm 'git restore --source origin/main'
abbr yolo 'git commit --amend --no-edit && git push --force'
abbr yeet 'git commit --amend --no-edit --no-verify && git push --force --no-verify'

abbr dcu 'docker compose up'
abbr dcr 'docker compose run --rm'

abbr ns 'nix-shell --run fish'
abbr nc 'sudo nix-collect-garbage -d'
abbr nb --set-cursor 'sudo nixos-rebuild switch --flake ~/nix#%'
abbr nr --set-cursor 'nix run nixpkgs#%'
abbr nq --set-cursor 'nix-store -q --requisites /nix/store/%'

abbr venv 'source .venv/bin/activate.fish'
abbr venvd 'source .venv/bin/deactivate.fish'
