vim.pack.add({
  "https://github.com/chrisgrieser/nvim-spider",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/nvim-lua/plenary.nvim",
  "https://github.com/nvim-telescope/telescope.nvim",
  "https://github.com/nvim-tree/nvim-web-devicons",
  "https://github.com/nvim-treesitter/nvim-treesitter-textobjects",
  "https://github.com/patrickswijgman/butter.nvim",
  "https://github.com/stevearc/conform.nvim",
  "https://github.com/vague-theme/vague.nvim",
})
