# https://catppuccin.com/palette/

[theme]
wallpaper     = "000000"
background    = "1e1e2e"
surface       = "313244"
text          = "cdd6f4"
border        = "89b4fa"
border_radius = 12
border_width  = 3
accent        = "eba0ac"

[theme.success]
background = "1e1e2e"
text       = "a6e3a1"
border     = "a6e3a1"

[theme.warning]
background = "1e1e2e"
text       = "f9e2af"
border     = "f9e2af"

[theme.danger]
background = "1e1e2e"
text       = "f38ba8"
border     = "f38ba8"
