# https://catppuccin.com/palette/

[theme]
wallpaper     = "181825"
background    = "1e1e2e"
surface       = "313244"
text          = "cdd6f4"
border        = "89b4fa"
border_radius = 12
border_width  = 3
accent        = "eba0ac"

[theme.danger]
background = "1e1e2e"
text       = "f38ba8"
border     = "f38ba8"
