words = [
    "Alacritty",
    "JIT",
    "arglead",
    "autocmds",
    "autoindent",
    "autotrigger",
    "breakindent",
    "bufnr",
    "buftype",
    "catppuccin",
    "cclose",
    "cexpr",
    "chezmoi",
    "cnext",
    "colorcolumn",
    "completeopt",
    "copen",
    "cprev",
    "cursorline",
    "efm",
    "esc",
    "expandtab",
    "fzf",
    "hlsearch",
    "ignorecase",
    "inccommand",
    "incsearch",
    "keymaps",
    "luarc",
    "mapleader",
    "maplocalleader",
    "menuone",
    "mkdir",
    "nargs",
    "netrw",
    "nohl",
    "nop",
    "noselect",
    "nowait",
    "nvim",
    "nzzzv",
    "pumborder",
    "quickfixtextfunc",
    "relativenumber",
    "scrolloff",
    "shiftwidth",
    "showbreak",
    "showmatch",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitbelow",
    "splitright",
    "swapfile",
    "tabstop",
    "timeoutlen",
    "trimempty",
    "undofile",
    "updatetime",
    "vimgrep",
    "winborder",
    "winid",
]
