words = [
    "bufnr",
    "cmdline",
    "formatters",
    "gofmt",
    "jit",
    "keymap",
    "keymaps",
    "lualine",
    "nixfmt",
    "nvim",
    "prettierd",
    "rustfmt",
    "statusline",
    "stylua",
    "subword",
    "taplo",
    "vimgrep",
]
