words = [
    "JIT",
    "arglead",
    "autocmds",
    "autoindent",
    "autotrigger",
    "bufnr",
    "buftype",
    "colorcolumn",
    "completeopt",
    "cursorline",
    "efm",
    "esc",
    "expandtab",
    "fzf",
    "hlsearch",
    "ignorecase",
    "inccommand",
    "incsearch",
    "keymaps",
    "luarc",
    "mapleader",
    "menuone",
    "nargs",
    "netrw",
    "nohl",
    "noselect",
    "nowait",
    "pumborder",
    "quickfixtextfunc",
    "relativenumber",
    "scrolloff",
    "shiftwidth",
    "showmatch",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitbelow",
    "splitright",
    "swapfile",
    "tabstop",
    "trimempty",
    "undofile",
    "updatetime",
    "vimgrep",
    "winborder",
]
