require("lsp").setup({
  enabled = {
    "biome",
    "codebook",
    "css_variables",
    "cssls",
    "cssmodules_ls",
    "docker_language_server",
    "efm",
    "emmet_language_server",
    "fish_lsp",
    "gitlab_ci_ls",
    "golangci_lint_server",
    "gopls",
    "jinja_lsp",
    "jsonls",
    "lua_ls",
    "pylsp",
    "ruff",
    "rust_analyzer",
    "spectral",
    "nixd",
    "stylua",
    "taplo",
    "vtsls",
    "yamlls",
  },
  format = true,
  formatter_priority = {
    "biome",
    "efm",
  },
  code_actions = {
    biome = {
      "source.fixAll.biome",
    },
  },
  semantic_tokens = false,
  auto_complete = true,
  auto_complete_auto_trigger = true,
  timeout_ms = 1000,
})
