require("bulb").setup({
  servers = {
    "biome",
    "codebook",
    "cssls",
    "cssmodules_ls",
    "docker_language_server",
    "emmet_language_server",
    "fish_lsp",
    "golangci_lint_server",
    "gopls",
    "jinja_lsp",
    "jsonls",
    "lua_ls",
    "nixd",
    "pylsp",
    "ruff",
    "taplo",
    "vtsls",
    "yamlls",
  },
  semantic_tokens = false,
  completion = {
    enable = true,
    autotrigger = true,
    autotrigger_chars = require("bulb").all_chars,
  },
})
