require("lsp").setup({
  enabled = {
    "biome",
    "codebook",
    "cssls",
    "cssmodules_ls",
    "docker_language_server",
    "efm",
    "emmet_language_server",
    "fish_lsp",
    "golangci_lint_server",
    "gopls",
    "jinja_lsp",
    "jsonls",
    "lua_ls",
    "nixd",
    "pylsp",
    "ruff",
    "rust_analyzer",
    "stylua",
    "taplo",
    "vtsls",
    "yamlls",
  },
  semantic_tokens = false,
  auto_complete = {
    enable = true,
    auto_trigger = true,
    auto_trigger_on_all_chars = true,
  },
  format = {
    enable = true,
    priority = {
      "biome",
      "efm",
    },
    code_actions = {
      biome = { "source.fixAll.biome" },
    },
    timeout_ms = 1000,
  },
})
