require("conform").setup({
  formatters_by_ft = {
    javascript = { "biome", "prettier", stop_after_first = true },
    typescript = { "biome", "prettier", stop_after_first = true },
    javascriptreact = { "biome", "prettier", stop_after_first = true },
    typescriptreact = { "biome", "prettier", stop_after_first = true },
    html = { "prettierd" },
    css = { "prettierd" },
    json = { "biome", "prettier", stop_after_first = true },
    jsonc = { "biome", "prettier", stop_after_first = true },
    yaml = { "prettierd" },
    markdown = { "prettierd" },
    lua = { "stylua" },
    nix = { "nixfmt" },
    go = { "gofmt" },
    rust = { "rustfmt" },
    python = { "ruff" },
    toml = { "taplo" },
    _ = { "trim_whitespace" },
  },
  format_on_save = {
    timeout_ms = 2000,
    lsp_format = "fallback",
  },
})
