theme = "catppuccin_mocha"

[editor]
scrolloff               = 8
shell                   = ["fish", "-c"]
cursorline              = true
bufferline              = "multiple"
color-modes             = true
end-of-line-diagnostics = "hint"

[editor.statusline]
left   = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right  = ["diagnostics", "workspace-diagnostics", "spacer", "file-type", "selections", "position", "total-line-numbers"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff", "spacer"]

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"

# See a list of all available commands here:
# https://docs.helix-editor.com/commands.html

[keys.normal]
"w"     = "move_next_sub_word_start"
"b"     = "move_prev_sub_word_start"
"e"     = "move_next_sub_word_end"
"q"     = "no_op"
"Q"     = "no_op"
"x"     = "select_line_below"
"X"     = "select_line_above"
"Y"     = ["extend_to_line_bounds", "yank"]
"D"     = ["extend_to_line_bounds", "delete_selection"]
"C-r"   = "redo"
"C-h"   = "goto_previous_buffer"
"C-l"   = "goto_next_buffer"
"C-q"   = ":buffer-close"
"C-tab" = "goto_last_accessed_file"
"esc"   = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
"esc" = ["collapse_selection", "normal_mode"]

[keys.select]
"w"   = "extend_next_sub_word_start"
"b"   = "extend_prev_sub_word_start"
"e"   = "extend_next_sub_word_end"
"C-d" = ["search_selection", "extend_search_next"]
"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
