theme = "fleet_dark"

[editor]
scrolloff               = 8
shell                   = ["fish", "-c"]
line-number             = "relative"
cursorline              = true
completion-timeout      = 5
bufferline              = "multiple"
color-modes             = true
popup-border            = "all"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left   = ["mode", "spinner", "spacer", "diagnostics", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right  = ["file-type", "selections", "position", "position-percentage", "spacer"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff", "spacer"]

[editor.soft-wrap]
enable = true

[keys.normal]
"w"     = "move_next_sub_word_start"
"e"     = "move_next_sub_word_end"
"b"     = "move_prev_sub_word_start"
"q"     = "no_op"
"Q"     = "no_op"
"x"     = "select_line_below"
"X"     = "select_line_above"
"Y"     = ["extend_to_line_bounds", "yank"]
"D"     = ["extend_to_line_bounds", "delete_selection"]
"K"     = "hover"
"C-r"   = "redo"
"C-h"   = "goto_previous_buffer"
"C-l"   = "goto_next_buffer"
"C-q"   = ":buffer-close"
"C-d"   = ["search_selection_detect_word_boundaries", "select_mode", "search_next"]
"C-u"   = "no_op"
"C-tab" = "goto_last_accessed_file"
"A-h"   = "jump_view_left"
"A-j"   = "jump_view_down"
"A-k"   = "jump_view_up"
"A-l"   = "jump_view_right"
"esc"   = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
"C-space" = "completion"
"esc"     = ["collapse_selection", "normal_mode"]

[keys.select]
"w"   = "extend_next_sub_word_start"
"e"   = "extend_next_sub_word_end"
"b"   = "extend_prev_sub_word_start"
"C-d" = ["search_selection", "extend_search_next"]
"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
