[language-server.vtsls]
command = "vtsls"
args    = ["--stdio"]

[language-server.vtsls.config]
typescript.preferences.importModuleSpecifier       = "non-relative"
typescript.preferences.importModuleSpecifierEnding = "auto"

[language-server.biome]
command = "biome"
args    = ["lsp-proxy"]

[language-server.scls]
command = "simple-completion-language-server"

[language-server.codebook]
command = "codebook-lsp"
args    = ["serve"]

[[language]]
name             = "javascript"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome", "codebook", "scls"]
auto-format      = true

[[language]]
name             = "jsx"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome", "codebook", "scls"]
auto-format      = true

[[language]]
name             = "typescript"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome", "codebook", "scls"]
auto-format      = true

[[language]]
name             = "tsx"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome", "codebook", "scls"]
auto-format      = true

[[language]]
name             = "python"
language-servers = ["pyright", "ruff", "codebook", "scls"]
formatter        = { command = "ruff", args = ["format", "-"] }
auto-format      = true

[[language]]
name             = "go"
language-servers = ["gopls", "codebook", "scls"]
formatter        = { command = "gofmt" }
auto-format      = true

[[language]]
name             = "rust"
language-servers = ["rust-analyzer", "codebook", "scls"]
formatter        = { command = "rustfmt", args = ["--emit=stdout"] }
auto-format      = true

[[language]]
name             = "nix"
language-servers = ["nixd", "scls"]
formatter        = { command = "nixfmt" }
auto-format      = true

[[language]]
name             = "html"
language-servers = [{ name = "vscode-html-language-server", except-features = ["format"] }, "scls"]
formatter        = { command = 'prettierd', args = [".html"] }
auto-format      = true

[[language]]
name             = "css"
language-servers = [{ name = "vscode-css-language-server", except-features = ["format"] }, "scls"]
formatter        = { command = 'prettierd', args = [".css"] }
auto-format      = true

[[language]]
name             = "json"
language-servers = [{ name = "vscode-json-language-server", except-features = ["format"] }, "biome", "scls"]
auto-format      = true

[[language]]
name             = "jsonc"
language-servers = [{ name = "vscode-json-language-server", except-features = ["format"] }, "biome", "scls"]
auto-format      = true

[[language]]
name             = "markdown"
language-servers = ["codebook", "scls"]
formatter        = { command = 'prettierd', args = [".md"] }
auto-format      = true

[[language]]
name             = "yaml"
language-servers = ["yaml-language-server", "scls"]
formatter        = { command = "prettierd", args = [".yaml"] }
auto-format      = true

[[language]]
name             = "toml"
language-servers = ["taplo", "scls"]
auto-format      = true
