[language-server.typescript-language-server.config]
preferences.importModuleSpecifierPreference = "non-relative"
preferences.importModuleSpecifierEnding = "js"

[language-server.vscode-json-language-server.config]
json.schemas = [{ fileMatch = ["package.json"], url = "https://json.schemastore.org/package.json" }, { fileMatch = ["tsconfig.json", "tsconfig.*.json"], url = "https://json.schemastore.org/tsconfig.json" }]
json.validate.enable = true

[[language]]
name = "nix"
language-servers = ["nixd"]
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format = true
roots = ["."]
