# See default configuration of all languages here:
# https://github.com/helix-editor/helix/blob/25.01.1/languages.toml

[language-server.scls]
command = "simple-completion-language-server"

[language-server.taplo.config]
root_dir = [".git", "*.toml"] # Make the LSP also work outside Git repositories.

[[language]]
name        = "toml"
file-types  = ["toml", { glob = "poetry.lock" }, { glob = "Cargo.lock" }, { glob = "*.toml.tmpl" }]
auto-format = true

[[language]]
name             = "nix"
language-servers = ["nixd"]
formatter        = { command = "nixfmt" }
auto-format      = true

[[language]]
name             = "typescript"
language-servers = ["typescript-language-server", "scls"]
formatter        = { command = "prettierd", args = [".ts"] }
auto-format      = true

[[language]]
name             = "tsx"
language-servers = ["typescript-language-server", "scls"]
formatter        = { command = "prettierd", args = [".ts"] }
auto-format      = true
