# See default configuration of all languages here:
# https://github.com/helix-editor/helix/blob/25.01.1/languages.toml

[language-server.scls]
command = "simple-completion-language-server"

[language-server.typos]
command = "typos-lsp"

[language-server.typescript-language-server.config]
preferences.importModuleSpecifierPreference = "non-relative"
preferences.importModuleSpecifierEnding     = "js"

[language-server.taplo.config]
root_dir = [".git", "*.toml"] # Make the LSP also work outside Git repositories.

[[language]]
name             = "typescript"
language-servers = ["typescript-language-server", "vscode-eslint-language-server", "scls", "typos"]
formatter        = { command = "prettierd", args = [".ts"] }
auto-format      = true

[[language]]
name             = "tsx"
language-servers = ["typescript-language-server", "vscode-eslint-language-server", "tailwindcss-ls", "scls", "typos"]
formatter        = { command = "prettierd", args = [".tsx"] }
auto-format      = true

[[language]]
name             = "python"
language-servers = ["basedpyright", "ruff", "scls", "typos"]
formatter        = { command = "ruff", args = ["format", "-"] }
auto-format      = true

[[language]]
name             = "go"
language-servers = ["gopls", "golangci-lint-lsp", "scls", "typos"]
formatter        = { command = "gofmt" }
auto-format      = true

[[language]]
name             = "rust"
language-servers = ["rust-analyzer", "scls", "typos"]
formatter        = { command = "rustfmt", args = ["--emit=stdout"] }
auto-format      = true

[[language]]
name             = "nix"
language-servers = ["nixd", "typos"]
formatter        = { command = "nixfmt" }
auto-format      = true

[[language]]
name        = "html"
formatter   = { command = 'prettierd', args = [".html"] }
auto-format = true

[[language]]
name        = "css"
formatter   = { command = 'prettierd', args = [".css"] }
auto-format = true

[[language]]
name        = "json"
formatter   = { command = 'prettierd', args = [".json"] }
auto-format = true

[[language]]
name        = "jsonc"
formatter   = { command = 'prettierd', args = [".jsonc"] }
auto-format = true

[[language]]
name        = "markdown"
formatter   = { command = 'prettierd', args = [".md"] }
auto-format = true

[[language]]
name        = "yaml"
formatter   = { command = "prettierd", args = [".yaml"] }
auto-format = true

[[language]]
name        = "toml"
file-types  = ["toml", { glob = "poetry.lock" }, { glob = "Cargo.lock" }, { glob = "*.toml.tmpl" }]
auto-format = true
