# See https://github.com/helix-editor/helix/blob/25.01.1/languages.toml for the default language configs.
# See https://docs.helix-editor.com/master/languages.html for documentation.

[language-server.taplo.config]
root_dir = [".git", "*.toml"] # Make the LSP also work outside Git repositories.

[[language]]
name        = "toml"
auto-format = true

[[language]]
name             = "nix"
language-servers = ["nixd"]
formatter        = { command = "nixfmt" }
auto-format      = true
