require("config.options")
require("config.keymaps")
require("config.autocmds")

require("plugins.catppuccin")
require("plugins.auto-session")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.conform")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.surround")
require("plugins.neogit")
require("plugins.spider")
require("plugins.colorizer")
require("plugins.arrow")
