require("config.options")
require("config.keymaps")

require("plugins.rose-pine")
require("plugins.auto-session")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.conform")
require("plugins.telescope")
require("plugins.neo-tree")
