require("config.options")
require("config.keymaps")
require("config.autocmds")

-- Require colorscheme as the first plugin because of highlight groups.
require("plugins.catppuccin")

require("plugins.arrow")
require("plugins.auto-session")
require("plugins.cmp")
require("plugins.colorizer")
require("plugins.conform")
require("plugins.lsp")
require("plugins.neogit")
require("plugins.neotest")
require("plugins.nvim-tree")
require("plugins.spider")
require("plugins.surround")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.which-key")
