[general]
import = ["./themes/catppuccin-mocha.toml"]

[window]
padding.x       = 4
padding.y       = 4
dynamic_padding = true

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"
style  = "Regular"

[[keyboard.bindings]]
key    = "N"
mods   = "Control|Shift"
action = "SpawnNewInstance"
