[window]
padding = { x = 4, y = 0 }
dynamic_padding = true

[font]
size = 12

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"
